name: Remove 'agenda' label from discussions

on:
  workflow_dispatch:

jobs:
  remove_agenda_label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'

    - name: Install octokit/request.js
      run: npm install @octokit/request@8

    - name: Remove 'agenda' label from discussions
      uses: actions/github-script@v6
      env:
        REPO_OWNER: utnim2
        REPO_NAME: CI-CD-test
        MY_TOKEN: ${{ secrets.PAT_KEY }}
      with: 
        script: |
          const { Octokit } = require('@octokit/request');
    
          const octokit = new Octokit({
            auth: process.env.MY_TOKEN,
          });
    
          async function removeAgendaLabel() {
            try {
              const { data: discussions } = await octokit.request.graphql(
                `
                query ($owner: String!, $repo: String!, $label: String!) {
                  repository(owner: $owner, name: $repo) {
                    discussions(labels: [$label], first: 10) {
                      nodes {
                        id
                        title
                      }
                    }
                  }
                }
                `,
                {
                  owner: process.env.REPO_OWNER,
                  repo: process.env.REPO_NAME,
                  label: 'agenda'
                }
              );
    
              for (const discussion of discussions.repository.discussions.nodes) {
                await octokit.request.graphql(
                  `
                  mutation ($discussionId: ID!, $labelId: String!) {
                    removeLabelsFromDiscussion(input: {id: $discussionId, labelIds: [$labelId]}) {
                      clientMutationId
                    }
                  }
                  `,
                  {
                    discussionId: discussion.id,
                    labelId: 'agenda'
                  }
                );
                console.log(`'agenda' label removed from discussion: ${discussion.title}`);
              }
            } catch (error) {
              console.error(error);
              process.exit(1);
            }
          }
    
          removeAgendaLabel();
