name: Search for issues and PR labeled 'agenda' and add them to the agenda

on:
  workflow_dispatch:
  repository_dispatch:
    types: remove-agenda-label

jobs:
  search_and_add:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove 'agenda' label from issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const octokit = require('@octokit/core').Octokit  
          const mygithub = new octokit({
            auth: process.env.GITHUB_TOKEN
          });
          const owner = 'Min2who';
          const repo = 'CI-CD-test';
          const issueNumber = 1;
          await mygithub.issues.removeLabel({
            owner,
            repo,
            issue_number: issueNumber,
            name: 'agenda'
          });
