name: Search for issues and PR labeled 'agenda' and add them to the agenda

on:
  workflow_dispatch:

jobs:
  search_and_add:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install @octokit/request@5

    - name: Remove 'agenda' label from discussion
      run: |
        const { request } = require('@octokit/request');

        const accessToken = process.env.GITHUB_TOKEN;
        const owner = 'Min2who';
        const repo = 'CI-CD-test';
        const discussionNumber = 1; 
        const appendLabel = 'agenda';

        try {
          await request({
            method: 'DELETE',
            url: `/repos/${owner}/${repo}/discussions/${discussionNumber}/labels/${appendLabel}`,
            headers: {
              authorization: `token ${accessToken}`,
              accept: 'application/vnd.github.v3+json',
            },
          });
          console.log('Label removed successfully.');
        } catch (error) {
          console.error('Error removing label:', error.message);
        }
